name: accelerate_rest
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  uuid: ^2.0.4
  http: ^0.12.0+4